### ISSUE TITLE
 Can't resolve 'window' in 'project/node_modules/jquery/dist'

### ISSUE THREAD

**Issue by Hongbusi** [webpack-contrib/imports-loader#122]
### Bug report

``` bash
Can't resolve 'window' in 'project/node_modules/jquery/dist'
Can't resolve 'var define = false' in 'project/node_modules/jquery/dist'
```

### Actual Behavior

In `webpack@5.68.0` + `imports-loader@3.1.1` can not work.

In webpack.config.js:

``` js
{
    test: new RegExp(`(${regExp.join('|')})$`),
    use: [
      {
        loader: 'imports-loader',
        options: {
          additionalCode: 'var define = false; var module = false; var exports = false;',
          wrapper: 'window'
        }
      }
    ]
 }
```

In `webpack@4.41.2` + `imports-loader@0.8.0` normal work.

In webpack.config.js:

``` js
{
    test: new RegExp(`(${regExp.join('|')})$`),
    loader: 'imports-loader?define=>false&module=>false&exports=>false&this=>window',
}
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

``` bash
  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 595.60 MB / 8.00 GB
  Binaries:
    Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v12.22.7/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 95.0.2
    Safari: 15.1
  Packages:
    es-webpack-engine: ^4.6.0 => 5.0.0
```

**Comment by alexander-akait** [comment]
Can you provide reproducible example? I think you try to wrapper already wrapped function

**Comment by Hongbusi** [comment]
> 你能提供可重现的例子吗？我认为您尝试包装已经包装的功能

Thanks for your answer, I think so too. 

But one thing I can't understand is that the same code, why is it normal in v0.8.0, but the latest version will have this problem?

**Comment by Hongbusi** [comment]
> Can you provide reproducible example? I think you try to wrapper already wrapped function

Thanks for your answer, I think so too.

But one thing I can't understand is that the same code, why is it normal in v0.8.0, but the latest version will have this problem?

**Comment by Hongbusi** [comment]
> Because we do refactor and change some logic

To upgrade to the latest version, are there any good solutions or ideas for this problem?

Thank you!

**Comment by alexander-akait** [comment]
Please provide reproducible example, I don't know your code, so hard to say what is wrong

**Comment by Hongbusi** [comment]
> Why you don't parse `jquery`?

All noParse modules in the configuration file(https://github.com/edusoho/edusoho/blob/master/webpack.config.js#L41) will report the above error.

**Comment by alexander-akait** [comment]
How you run webpack? I can't found `scripts`

**Comment by Hongbusi** [comment]
> How you run webpack? I can't found `scripts`

By executing node api:
- https://github.com/edusoho/edusoho/blob/master/package.json#L112
- https://github.com/Hongbusi/es-webpack-engine/blob/4.x/src/webpack.dev.js#L21

**Comment by alexander-akait** [comment]
Sorry, I can't run your configuration without problems, I got:
```
[webpack-cli] Failed to load '/home/evilebottnawi/IdeaProjects/es-webpack-engine/src/webpack.dev.js' config
[webpack-cli] Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options.patterns should be a non-empty array.
```

Using ` webpack --config src/webpack.dev.js`, please provide steps to reproducible the problem

**Comment by Hongbusi** [comment]
Sorry to bother you again, might need your help to provide some ideas. @alexander-akait

**Comment by alexander-akait** [comment]
@Hongbusi Can you reduce complex of the reproducible? I still can't run your example
