### ISSUE TITLE
imports-loader breaks "use strict"

### ISSUE THREAD

**Issue by justjake** [webpack-contrib/imports-loader#13]
## Context

somewhere in my dependency graph, I have a file with a format like this:

```
if (typeof define === 'function') {
  // do some AMD stuff with `define`
} else {
 var foo = require('etc etc etc');
}
```

If webpack parses this without `imports-loader?define=>false`, then it tries to resolve a bunch of AMD modules that I don't have, since I am using `npm` and commonjs. So I have this in my config file:

```
module: {
  loaders: [
    // try to totally disable AMD shit since we're just commonjs here
    // this gets "universal" modules to skip trying to use AMD, since we
    // don't have any of the dependecies set up in that case.
    // @see https://github.com/webpack/imports-loader#disable-amd
    {
      test: /./,
      loader: 'imports-loader?define=>false',
    },
    // ... more loaders
  ]
}
```
## Issue

However, I see that imports-loader is inserting variables before any `"use strict";` directives in my modules or my dependencies:
![sadness occurs here](http://take.ms/VZojH)

is there a better way to disable AMD in webpack? Is there a way to move "use strict"; above the imports-injected variables?

**Comment by PerlPong** [comment]
I have the exact same issue.

**Comment by dfguo** [comment]
Having the same issue too. Took some time to figure that this is the issue.

**Comment by mikeapr4** [comment]
Use the https://www.npmjs.com/package/strict-loader

    module: {
      loaders: [
        {
          test: /./,
          loader: 'strict!imports-loader?define=>false',
        },
      ]
    }
