### ISSUE TITLE
regex syntax typo

### ISSUE THREAD

**Issue by Tchiller** [webpack-contrib/imports-loader#139]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] wrong

### Please Explain in Detail...

In your docu you write:

```
// You can use `regexp`
// test: /example\.js/$
```
I guess the dollar sign should stand before the slash and not behind

### Your Proposal for Changes

```
// You can use `regexp`
// test: /example\.js$/
```

Thank you. Hope that helps.

**Comment by alexander-akait** [comment]
PR welcome
