### ISSUE TITLE
This line `toString`  should be `toJSON`

### ISSUE THREAD

**Issue by MXXXXXS** [webpack-contrib/imports-loader#141]
https://github.com/webpack-contrib/imports-loader/blob/1d8f8c3ce401ac7b415863e0e658ebdb8ec489fb/src/index.js#L106

https://github.com/babel/babel/pull/14658

It will cause error when using with babel-loader like

```
Error: .inputSourceMap must be a boolean, object, or undefined
    at assertInputSourceMap (/home/aqua/coding/atri/node_modules/@babel/core/lib/config/validation/option-assertions.js:124:11)
```

**Comment by alexander-akait** [comment]
`toString` and `toJSON` returns string, don't think you are right here

**Comment by MXXXXXS** [comment]
![image](https://user-images.githubusercontent.com/28096993/178652309-c0900cdf-e13b-4941-b7c7-827d21d9853a.png)

@alexander-akait Strange... `toJSON` actually returns an object

And babel-loader not recognise string, it should be an object

**Comment by alexander-akait** [comment]
Please create reproducible test repo, babel-loader should handle string source maps (as minimum it worker early)

**Comment by MXXXXXS** [comment]
@alexander-akait Here is: https://github.com/MXXXXXS/import-loader-bug

Run `npm i && npm run build`, and it will output like:

```
-> % npm run build

> import-loader-bug@1.0.0 build
> webpack

asset app.js 1.67 KiB [emitted] (name: app) 1 related asset
./src/app.js 39 bytes [built] [code generated] [1 error]

ERROR in ./src/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .inputSourceMap must be a boolean, object, or undefined
    at assertInputSourceMap (/home/aqua/coding/import-loader-bug/node_modules/@babel/core/lib/config/validation/option-assertions.js:124:11)
```

**Comment by rectalogic** [comment]
Confirmed the above patch fixes this issue for us.
