### ISSUE TITLE
when using both 'babel-loader' and 'imports-loader', `this=>window` will not work

### ISSUE THREAD

**Issue by illusory-love** [webpack-contrib/imports-loader#23]
webpack.config.js 

``` js
{ test: /\.js$/, loader: 'envify!babel'}
```

this is wrong

``` js
!function (a, b) {
      "function" == typeof define && (define.amd || define.cmd) ? define(function () {
        return b(a);
      }) : b(a, !0);
    }(undefined, function (a, b) {}.call(window));
```

this is correct

``` js
!function (a, b) {
      "function" == typeof define && (define.amd || define.cmd) ? define(function () {
        return b(a);
      }) : b(a, !0);
    }(this, function (a, b) {}.call(window));
```

**Comment by sinn1** [comment]
Is this the cause of the proble I'm having:

`
//./alert.js to import
(function(window) { 
  alert(window); 
})(this)


// import
require('imports?this=>window!./alert.js')

// resolved to
(function() {
  (function(window) {
    alert(window);
   })(undefined)
}.call(window));
`

Is there a work around?

**Comment by jdub** [comment]
I've noticed that if I put my `imports-loader` block after `babel-loader`, I get the expected output (with `this` instead of `undefined`).

**Comment by evilebottnawi** [comment]
Yes, you need put `babel-loader` before `imports-loader`
