### ISSUE TITLE
Using Alias does not work

### ISSUE THREAD

**Issue by DutchKevv** [webpack-contrib/imports-loader#25]
When doing something like this 

```
require('imports?this=>global!bootstrap');
```

Where bootstrap is defined as an alias

```
resolve: {
    alias: {
        // Bootstrap
        'bootstrap'             : path.join(PATH_JS_VENDOR, 'bootstrap/bootstrap'),
    }
},
```

doesn't seem to work

**Comment by DXCanas** [comment]
Also running into this. Might it have something to do with the webpack's `context`?

**Comment by DutchKevv** [comment]
This topic is closed now, is it fixed .. ?

**Comment by evilebottnawi** [comment]
Yes, ETA is tomorrow

**Comment by evilebottnawi** [comment]
If you faces with this issue again after release, feel free to open a new issue with reproducible test repo/configuration/example of code
