### ISSUE TITLE
`imports?window.jQuery=jquery` doesn't capture window

### ISSUE THREAD

**Issue by groner** [webpack-contrib/imports-loader#37]
The expression `imports?window.jQuery=jquery!angular` generates the following 
```javascript
/*** IMPORTS FROM imports-loader ***/
var window = (window || {});
window.jQuery = require("jquery");

require('./angular');
```

When webpack wraps this in a function expression, the `window` referenced in the initialization of the local`window` is the local `window` rather than the global `window`.  This is fine for contained modules, but in this case the module is just a stub that loads another module where the private `window` isn't visible.

**Comment by cdauth** [comment]
I am using exactly the same expression, but for me the imports-loader additionally inserts the some code into the angular module itself:

```javascript
/* 5 */
/***/ function(module, exports, __webpack_require__) {

	/*** IMPORTS FROM imports-loader ***/
	var window = (window || {});
	window.jQuery = __webpack_require__(3);

	/**
	 * @license AngularJS v1.6.1
	 * (c) 2010-2016 Google, Inc. http://angularjs.org
	 * License: MIT
	 */
	(function(window) {'use strict';
```

For some reason though, this `window` object is broken and for example doesn't contain `document`. I don't really understand why, I will try to investigate.

**Comment by amitayr** [comment]
@cdauth this happens because of javascript hoisting.
this line:
`var window = (window || {});`
is interpreted as 
`var window;
window = (window || {});`
so you don't get the global window varaible.

you can solve it with some hacking:
`imports-loader?window=>global&window.jQuery=>jquery!angular`
or 
`imports-loader?windowTemp=>window&windowTemp.jQuery=>jquery!angular`

**Comment by Lazarencjusz** [comment]
You can provide jQuery by adding plugin:

```
plugins: [
         new webpack.ProvidePlugin({
             $: "jquery",
             jQuery: "jQuery"
         })
]
```

**Comment by cap-Bernardito** [comment]
After the release, you can solve this problem like this:

```js
module.exports = {
  module: {
    rules: [
      {
        test: require.resolve('example.js'),
        use: [
          {
            loader: 'imports-loader',
            options: {
              type: 'commonjs',
              imports: {
                moduleName: 'jquery',
                name: 'jQuery',
              },
              aditionalCode: 'window.jQuery = jQuery';
            },
          },
        ],
      },
    ],
  },
};

// Adds the following code to the beginning of example.js:
//
// var jQuery = require("jquery");
// window.jQuery = jQuery
```

Release will be soon.

**Comment by Tchiller** [comment]
@cap-Bernardito  thanks for your last comment. Should this work in imports-loader 1? (can't go higher as I am still not able to update to webpack 5. 

I tried your code but am getting 

```
ERROR in ./lib/jquery-ui-addon-autosize.js
Module not found: Error: Can't resolve 'window.jQuery = jQuery' in '/home/node/app/client/lib'
```

By the way, there was a typo in your last comment which you might want to correct. "additionalCode"

Thank you.
