### ISSUE TITLE
Webpack 2?

### ISSUE THREAD

**Issue by kentcdodds** [webpack-contrib/imports-loader#38]
Does this loader support Webpack 2? If so, how would you specify the options with the new `rules` API?

For example. I have this:
```javascript
{
    test: /globalize/,
    loader: 'imports?define=>false',
},
```

I was thinking:

```javascript
{
    test: /globalize/,
    use: [{ loader: 'imports-loader', options: { 'define=>false': '' } }],
}
```

But I'm unsure, and it seems odd...

**Comment by TheLarkInn** [comment]
That actually might be something that works. It's like you mentioned the `=>` which is the unconventional piece thats parsed [here](https://github.com/webpack/imports-loader/blob/master/index.js#L14-L45). 

If you didn't have to use the `=> syntax, how would you imagine it working.

**Comment by kentcdodds** [comment]
Yeah, honestly, the whole thing's kinda whacky... I tried the above code and that didn't work. Not sure how to make it work properly so I'm using the old query string API for now... :-/

**Comment by TheLarkInn** [comment]
I mean, it looks like these symbols (first time even looking at this loader), to expand into expressions. Would it make it undesirable to just pick the type of expression needed.

**Comment by kentcdodds** [comment]
Yeah, honestly, I'm not a huge fan of the syntax as it is... It's pretty overloaded (just look at the table). I would rather something simpler, like:

Option value | Equals
------------|-------
`angular: 'require("angular")'` | `var angular = require("angular");`
`$: 'require("jquery")` | `var $ = require("jquery");`
`define: 'false'` | `var define = false;`
`config: '{size:50}'` | `var config = {size:50};`
`'this': 'window'` | `(function () { ... }).call(window);`

Notice that the only special case is the last one because that's kinda hard to represent in any other way... Thoughts?

**Comment by djedje72** [comment]
This syntax seems to work too: 

`
loader: 'imports-loader', 
   options: {
      define: ">false",
      module: ">false"
}
`

**Comment by ahmedelgabri** [comment]
I'm using this and it still working for me:

```js
{ 
  test: require.resolve('foo'), 
  use: ['imports-loader?this=>window', 'exports-loader?foo'] 
}
```

**Comment by Vanuan** [comment]
This what is printed for me:


```
loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

```

**Comment by d3viant0ne** [comment]
@Vanuan - That is a deprecation warning from `loader-utils`

**Comment by Vanuan** [comment]
sorry, you're right, it's unrelated.

**Comment by Vanuan** [comment]
I've resolved my issue using a built-in option:

```
module: {
  rules: [
    { parser: { amd: false } }
  ]
}
```
