### ISSUE TITLE
Module build failed: SyntaxError: unexpected token (2:5)

### ISSUE THREAD

**Issue by bbyler** [webpack-contrib/imports-loader#46]
Nice work with imports-loader! 

I'm seeing errors of the following form, which are being thrown for many libraries (not specifically jQuery) while importing (see attached): 

![screen shot 2017-03-30 at 9 44 10 am](https://cloud.githubusercontent.com/assets/1127301/24507079/7cee41d2-152d-11e7-92f0-fb6a30807dc6.png)

My webpack.config.js is using webpack 2 and is patterned as: 

```js
const config = {
    entry: ...,
    ...,
    resolve: {
        modules: ['.', 'node_modules'],
        alias: {
            ...,

            'jQuery': path.resolve('node_modules/jquery/dist/jquery.min'),
            '$': path.resolve('node_modules/jquery/dist/jquery.min'),
            'jquery': path.resolve('node_modules/jquery/dist/jquery.min'),
            
            ...
        },
        module: {
            loaders: [
                {test: /\(js|jsx)$/, use: 'babel-loader'}
            ]
        },
        plugins: [
            new webpack.optimize.UglifyJsPlugin({minimize: true}),
            new webpack.ProvidePlugin({
                '$': 'jQuery',
                'jQuery': 'jquery',
                ...
            }),
            ...
        ]
    }
}
```

Any help would be greatly appreciated!

**Comment by michael-ciniawsky** [comment]
@bbyler in your `webpack.config.js` you use`webpack.ProvidePlugin` but not `imports-loader` 😛 
I need more info please, maybe it's in `ProvidePlugin` or a configuration problem of yours somewhere

**Comment by michael-ciniawsky** [comment]
```diff
new webpack.ProvidePlugin({
-  '$': 'jQuery', // typo here ?
+  '$': 'jquery',
   'jQuery': 'jquery',
    ...
})
```

**Comment by bbyler** [comment]
@michael-ciniawsky thanks! I suppose that's part of the confusion: my understanding was that ProvidePlugin binds your variables/libraries of choice to the window object after the build process finishes (e.g. dependency resolution and linking), so that the ProvidePlugin really reads as ```window.$ = jQuery; ... ``` etc., and you're right, I'm not explicitly calling out import-loader anywhere in the config. I assume import-loader is being recognized from being installed through npm and passed through resolve.modules

I'm focusing on jQuery in this case because it's common and fixing this class of errors helps other libraries running into the same thing, but with the disadvantage being that jQuery is unique in regards to other libraries. For more background, it's an older version of jQuery (~1.11.1), which I hope is outside the realm of AMD adaptations being required (though I did try the amd: { jQuery: true } param). 

Also, this is intended as a migration from a vanilla commonjs config to webpack, so we're trying to incorporate webpack into the mix! Should be a big improvement, just a matter of working out the kinks

**Comment by michael-ciniawsky** [comment]
Please try with `imports-loader` and for your journey https://webpack.js.org is your best friend 😛

**Comment by bbyler** [comment]
From the looks of it, imports-loader is already in use, otherwise ```js /*** IMPORTS FROM imports-loader ***/``` probably wouldn't make much sense?

**Comment by michael-ciniawsky** [comment]
And where should this come from, I have no clue tbh 😛 , with the config you posted above this shouldn't be the case

**Comment by michael-ciniawsky** [comment]
And `ProvidePlugin` doesn't use `imports-loader` internally, I verified that in webpack slack already

**Comment by bbyler** [comment]
For starters, there's imports-loader/index.js, which is building the imports list when looping over each of the dependencies. Somewhere within here, 

```js
if(typeof query[name] == "string" && query[name].substr(0, 1) == ">") {
			value = query[name].substr(1);
		} else {
			var mod = name;
			if(typeof query[name] === "string") {
				mod = query[name];
			}
			value = "require(" + JSON.stringify(mod) + ")";
		}
		if(name === "this") {
			imports.push("(function() {");
			postfixes.unshift("}.call(" + value + "));");
		} else if(name.indexOf(".") !== -1) {
			name.split(".").reduce(function(previous, current, index, names) {
				var expr = previous + current;

				if(previous.length === 0) {
					imports.push("var " + expr + " = (" + current + " || {});");
				} else if(index < names.length-1) {
					imports.push(expr + " = " + expr + " || {};");
				} else {
					imports.push(expr + " = " + value + ";");
				}

				return previous + current + ".";
			}, "");
		} else {
			imports.push("var " + name + " = " + value + ";");
		}
```

Interestingly enough, there are cases where the name is "true"...which would explain why there are some cases where we have ```var (blank) = ...```

**Comment by bbyler** [comment]
Just logging the name gives 

![screen shot 2017-03-30 at 3 21 11 pm](https://cloud.githubusercontent.com/assets/1127301/24522122/8b74a3f2-155c-11e7-9c0e-2649d92e11d7.png)

**Comment by bbyler** [comment]
so this is interesting: logging the full query object gives: 

![screen shot 2017-03-30 at 3 27 11 pm](https://cloud.githubusercontent.com/assets/1127301/24522391/664df2b2-155d-11e7-97ce-fc008c6927ea.png)

i.e. the name key is missing. looking into a solution...

**Comment by michael-ciniawsky** [comment]
Okay... so you using ìmports-loader? now and not `ProvidePlugin` and we have an eventual bug here? Do you use webpack 2 loader syntax or webpack v1 querystring syntax ?

**Comment by bbyler** [comment]
closing this one, i had a typo of the following form: 

```{test: /jquey/, loader: 'exports-loader?...!imports-loader?=jquery,...}```

The '=' is no good - stumbled upon it probably in an blog post/documentation doing something else

**Comment by michael-ciniawsky** [comment]
@bbyler Well I'm not 💯 if `exports-loader + imports-loader` work in conjunction and yep `imports-loader?=jquery => imports-loader?$=jquery` , I'm praying ES2015 Modules finally pick up some steam soon and things like that simply go away 😛
