### ISSUE TITLE
How test with Jest?

### ISSUE THREAD

**Issue by darkowic** [webpack-contrib/imports-loader#54]
I'm trying to setup Jest tests configuration for my project. I use imports-loader to load some old jQuery libs
```
import 'imports-loader!jquery-mousewheel'
```

When running tests with jest I get following error:
```
 Cannot find module 'imports-loader!jquery-mousewheel' from 'SomeModule.js'
```

As a workaround, I mock all imports-loader in Jest config
```json
"moduleNameMapper": {
  "imports-loader?.*": "<rootDir>/internals/mocks/importsLoader.js"
},
```
```js
// importsLoader.js
module.exports = 'IMPORTS_LOADER_MOCK';
````

How to configure it to actually import correct module?

**Comment by chacbumbum** [comment]
I have same issue. Have you solved it?

**Comment by darkowic** [comment]
Unfortunately no @chacbumbum

**Comment by maxcodes** [comment]
Bump. Stuck with the same issue

**Comment by nickangtc** [comment]
Thanks @darkowic I needed just a solution to mock all the `require('imports-loader!...')` blocks, your `moduleNameMapper` solution worked for me 👍

**Comment by am** [comment]
Facing the same issue but with `expose-loader`.

**Comment by technoligest** [comment]
Anyone had any luck with this? @darkowic  I do not completely understand your approach, can you please elaborate?

**Comment by darkowic** [comment]
The workaround simply imports string instead of the real module

**Comment by evilebottnawi** [comment]
Here a lot of examples - https://jestjs.io/docs/en/webpack, if somebody still have problems, please open an issue in jest
