### ISSUE TITLE
Add a JS library from folder

### ISSUE THREAD

**Issue by zhuyuanwen** [webpack-contrib/imports-loader#55]
In an original way, I reference the JS library globally by using the <script> tag. But it's not the way in webpack.
So I found 'imports-loader'. The problem is my JS library is not install by npm (like the jQuery or angular), it's in my src/assets/ folder.
How can I add my JS library to window object?

**Comment by qbaty** [comment]
Still you can use imports-loader or providePlugin, Just by setting resolve.alias to your local path
