### ISSUE TITLE
imports-loader doesn't work in combination with expose-loader

### ISSUE THREAD

**Issue by armaanahluwalia** [webpack-contrib/imports-loader#62]
Unfortunately, I don't have time to repro this issue but I'm very sure ( and have just confirmed) when imports-loader and expose-loader are both applied on the same file, doing imports loader this=>window will not work since the imports-loader will try to 'call' the additionally wrapped function generated by expose-loader instead of the actual module function.

**Solution**
Remove expose-loader on the file and imports-loader will start to work

**Comment by evilebottnawi** [comment]
Bug on `expose-loader` and will be fixed in near future
