### ISSUE TITLE
Using the imports-loader in a require statement ignores "externals" configuration

### ISSUE THREAD

**Issue by aholtkamp** [webpack-contrib/imports-loader#64]
Like the title says if I use the imports-loader like this:
```
require("imports-loader?jQuery=jquery!bootstrap-sass");
```

And I have an "externals" configuration provided in my webpack configuration:
```
{
   ...
  externals: {
    "bootstrap-sass": "jQuery"
  }
  ...
}
```

The externals configuration is ignored.

Workaround:
When configuring the "imports-loader" via webpack configuration:
```
{
  ...
  module: {
    rules: [
      {
        test: require.resolve("bootstrap-sass"),
        use: "imports-loader?jQuery=jquery",
      }
    ]
  }
}
```
everything works as expected.

Any chance this is getting fixed so in both cases the "externals" configuration is taken into account?

**Comment by ejoo** [comment]
@aholtkamp I don't see it is working

**Comment by cap-Bernardito** [comment]
The `externals` configuration is ignored, because `externals` based on module name.
Must specify:

```js
{
  externals: {
    "jquery": "jQuery"
  }
}
```
