### ISSUE TITLE
Can this be used to add a require with inline loaders?

### ISSUE THREAD

**Issue by dietergeerts** [webpack-contrib/imports-loader#65]
What I'm trying to do with a custom loader, is stop the chain in pitch phase, because I take another source file, but the rest of the chain (remainingRequest) should be added as an import/require, so I would use this imports-loader inline, but the name will have inline loaders too. Is there a way to escape the `!` or to use this with inline loaders?

**Comment by evilebottnawi** [comment]
Yes, it can be used with other inline loaders, sorry for delay, we need update docs
