### ISSUE TITLE
loader: require.resolve('imports-loader') instead of use 'imports-loader'

### ISSUE THREAD

**Issue by littlehome-eugene** [webpack-contrib/imports-loader#70]
I have several webpack.config.js in spread in different level of directories.

In a child webpack I do ` use: 'imports-loader?this=>window'`, and it looks for parent directory's `node_modules`. 

For other loaders I use form of `require.resolve("style-loader")` to use the current directory's node_modules library.

Can I use form of `require.resolve('imports-loader')` for ` use: 'imports-loader?this=>window'` ?

**Comment by evilebottnawi** [comment]
No don't use options in `use`, it is deprecated and will be removed in webpack@5
