### ISSUE TITLE
Request for Improved Readme

### ISSUE THREAD

**Issue by brendanw** [webpack-contrib/imports-loader#72]
> Since webpack is capable of both, they default to AMD in this case, which can be a problem if the implementation is quirky.

First, thanks for providing this loader. I've seen plug and chug usages in a few StackOverflow posts that have helped me troubleshoot an issue.

What does it mean if "the implementation is quirky"? I started moving a project that uses <script> tags in html to using webpack. I had a few issues trying to use the popular Datatables library. There are a number of copy and paste solutions offered on the Datatables forums and stackoverflow that make use of imports-loader. I'd like to understand why issues pop such as: this/window/$ is undefined.

The "Shimming Modules" link in the readme points to a dead page.

**Comment by cap-Bernardito** [comment]
Link to "Shimming Modules" fixed in master.
After the release, you will have more options for customization through webpack.config. Readmy will be update.

Release will be soon.
