### ISSUE TITLE
README: add Inline `additionalCode` example

### ISSUE THREAD

**Issue by wheeler** [webpack-contrib/imports-loader#81]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

I did some experimenting and it looks like you can specify `additionalCode` inline. Currently the examples are only of `type=` and `imports=`.

### Your Proposal for Changes
Add an example like:

```js
import myLib from 'imports-loader?additionalCode=var%20require%20=%20false;!./example.js';
// Adds the following code to the beginning of example.js:
// var require = false;
```

**Comment by evilebottnawi** [comment]
`additionalCode` is not good value for inline syntax, because you need escape spaces, in this case my recommendation is using webpack.config.js

**Comment by evilebottnawi** [comment]
Done, for simple case
