### ISSUE TITLE
Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by killmenot** [webpack-contrib/imports-loader#87]
- Operating System: Mac OS X
- Node Version: v14.12.0
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- imports-loader Version: 1.1.0

### Expected Behavior

No errors

### Actual Behavior

Invalid regular expression: invalid group specifier name
<img width="879" alt="Screenshot 2020-10-06 at 13 39 54" src="https://user-images.githubusercontent.com/119337/95191450-778da000-07d9-11eb-81da-14f1d41f9de3.png">

### Code

webpack.config.js
https://gist.github.com/killmenot/ca5f2efd020e7c5870fc671910e520b0

```js
// app.js
import 'imports-loader?this=>window|jquery.appear'
import 'imports-loader?window.jQuery=jquery|jquery-countto'

```

### How Do We Reproduce?

Open in Safari (Chrome works OK)

### Information
1. Problem was found after migration from 0.8.0 to 1.1.0 
2. Also, there is an open ticket here: https://github.com/jonschlinkert/strip-comments/issues/58

**Comment by cap-Bernardito** [comment]
Please provide a minimally reproducible test repository

**Comment by killmenot** [comment]
https://github.com/killmenot/imports-loader-87

**Comment by cap-Bernardito** [comment]
You are using the wrong syntax, and add the `imports-loader` itself to the bundle.
There have been big changes in version 1.0.0. Please read [them](https://github.com/webpack-contrib/imports-loader/releases/tag/v1.0.0) and the current [documentation](https://github.com/webpack-contrib/imports-loader).

You probably want something like this:

```js
import 'imports-loader?wrapper=window!jquery.appear'
import 'imports-loader?wrapper=window&imports=default|jquery|jQuery!jquery-countto'
```

If you are missing the inline syntax, you can use [webpack.config](https://github.com/webpack-contrib/imports-loader#using-configuration). There is a `additionalCode` option and advanced `wrapper` options available.

**Comment by killmenot** [comment]
Thanks!
