### ISSUE TITLE
'import' and 'export' may only appear at the top level 

### ISSUE THREAD

**Issue by chkpnt** [webpack-contrib/imports-loader#90]
- Operating System: macOS 10.15.7
- Node Version: 14.4.0
- NPM Version: 6.14.4
- webpack Version: 5.1.2
- imports-loader Version: 1.2.0

### Expected Behavior

According to #39, `imports-loader` should work with ES6 modules.

### Actual Behavior

I see the same issue as described in #39:

```
[...]
ERROR in ./src/foobar.js 4:0
Module parse failed: 'import' and 'export' may only appear at the top level (4:0)
File was processed with these loaders:
 * ./node_modules/imports-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| 
| (function() {
> export let bla = {
|     doSomething: function() {
|         console.log("this is " + this);
 @ ./src/index.js 1:0-31 3:0-15

webpack 5.1.2 compiled with 1 error in 156 ms
```

### Code
Please see the demonstration repo at https://github.com/chkpnt/imports-loader-issue.

### How Do We Reproduce?
Just execute `npm run-script dev` in the demonstration repo.

**Comment by cap-Bernardito** [comment]
As stated in the error - 'import' and 'export' may only appear at the top level of your file.
In other words, import/export don't work inside {}.

You can use CommonJS syntax instead:

```js
let bla = {
    doSomething: function() {
        console.log("this is " + this);
    }
}

module.exports = bla;
```

```js
const bla = require("./foobar");

bla.doSomething();
```

We will add this to the documentation

**Comment by chkpnt** [comment]
Thanks for the clarification! 👍
